packages:
  - packages/**
  - plugins/*/*
  - univer/*
  - builtin-plugins/*
  # vendored/bundled packages (not real workspaces)
  - '!plugins/native/napi-rs/*__*'
  - render-plugins/*
  - chatbots/**

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract

public-hoist-pattern:
  - '@pluxel/core'
  - '@pluxel/hmr'
