packages:
  - packages/**
  # vendored/bundled packages (not real workspaces)
  - '!packages/napi-rs/*__*'
  - render-plugins/*
  - chatbots/**

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract

public-hoist-pattern:
  - '@pluxel/core'
  - '@pluxel/hmr'
